### ISSUE TITLE
https://zh.fedoracommunity.org/ 上的文章没有声明 license

### ISSUE THREAD

**Issue by Endle** [FZUG/fzug.github.io#70]
个人建议，每篇文章都应该加上版权信息。如果有明确的作者，应该提供作者信息和作者原因以何种协议发布 （如 CC）。如果没有，建议 explicitly 声明文章属于 public domain

至于翻译的文章，在除提供原文的链接外，也应当提供原文的 license,译者信息以及译者的著作权说明

[中华人民共和国著作权法](http://www.npc.gov.cn/npc/c30834/202011/848e73f58d4e4c5b82f69d25d46048c6.shtml)
> 第十三条　改编、翻译、注释、整理已有作品而产生的作品，其著作权由改编、翻译、注释、整理人享有，但行使著作权时不得侵犯原作品的著作权。

翻译的著作权，也应当 explicit 声明其版权信息 (如放弃，则声明 public domain）

**Comment by alick** [comment]
@FZUG/pages-writer, 是否可以默认 CC BY-SA (Creative Commons Attribution-ShareAlike 4.0 International License)？（与大多数翻译文章的来源 fedoramagazine.org 保持一致）

https://fedoramagazine.org/terms-and-conditions/

如果没问题，可以新建个 pr，添加版权声明。

**Comment by alick** [comment]
ping @sztsian @geekpany

**Comment by alick** [comment]
fixed in #71
